---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "cfg4j - configuration library for Java distributed apps"
keywords:    "cfg4j, jvm, java, configuration, soa, web service, config, git, consul, zookeper, mysql, yaml, properties"
description: "cfg4j - configuration library for Java distributed apps"
source_link: "https://github.com/cfg4j/cfg4j"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-63861004-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  darkgray:  '#1d1d1d'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
